### PR TITLE
Fixed quick filter creation for listing libraries

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
This PR fixes the filters using the `Create Quick Filter...` action that would create a filter with wrong values for listing libraries.

### How to test this PR
1. Create a quick filter with value `Q*`
2. It must lists all the libraries starting with Q when expanded

### Checklist
* [x] have tested my change

### CODE REVIEW

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand Last review before bedtime:

There are some calls to `toUppercase()` in `createQuickFilter` - shouldn't these be changed to your uppercase routine?

**Comment by worksofliam** [comment]
@chrjorgensen is right about his suggested. Nonetheless, the fix works: 

image

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand So far my tests are positive. 👍 

But I'm having difficulties testing this PR with CCSID 297 - could you rebase it on master or merge master branch into this PR, so I can run the final tests?

**Comment by sebjulliand** [comment]
> @sebjulliand So far my tests are positive. 👍
> 
> But I'm having difficulties testing this PR with CCSID 297 - could you rebase it on master or merge master branch into this PR, so I can run the final tests?

And done! 🙌🏻

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand Quick Filter works fine now, including in CCSID 297. 👍 

I've fixed an error showing invalid member when a member was selected from recent files and having variants in the name.

Approved and merged. 🚀

**Comment by sebjulliand** [comment]
Brilliant @chrjorgensen , thank you!

**Pull request merged**
