### PR TITLE
Fix/run_action_tests

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

* [x] Provides fix for `runAction` where a prompt to ask the user if they want to see the output log was actually causing the API to never return until the user chose their option. This was stopping the action tests from running.
* [x] Fix for `postDownload` not downloading files in the root correctly.

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand Might need a hand looking at this bug with `postDownload`. I created a test case where I can recreate it.

Perhaps this is a Mac vs Windows thing?

**Comment by sebjulliand** [comment]
So...there was a couple of issues there.
- `getFile` / `getDirectory` / ... and all these methods don't like Windows path starting with a `/`. I fixed that in one place a while ago, so I moved the logic in one place and made sure every download/upload operation uses the correct method.
- The Action's post download process had multiple flaws in the logic (my bad!). Now, the type of what's downloaded is retrieved beforehand and local directories are created accordingly.
- We await for the downloads to end before returning from `runAction` (we used to not wait).
- The `post download test` tested the wrong file

I tested uploads and downloads all around and it all seems good. The post downloads are OK and the test runs fine.
@worksofliam hopefully it's still OK on Mac 😝  You'll tell me.

**Comment by worksofliam** [comment]
@sebjulliand Looks like the `postDownload` test is failing here:

image

```ts
{
  errno: -21,
  code: "EISDIR",
  syscall: "open",
  path: "/Users/barry/Downloads/ics/hello.txt",
  vslsStack: [
  ],
}
```

```json
"EISDIR: illegal operation on a directory, open '/Users/barry/Downloads/ics/hello.txt'"
```

---

`postDownloads` looks like this:

```ts
[
  {
    remotePath: "/tmp/vscodetemp-O_TJcXiWA6/hello.txt",
    localPath: "/Users/barry/Downloads/ics/hello.txt",
    type: 1,
  },
  {
    remotePath: "/tmp/vscodetemp-O_TJcXiWA6/random/",
    localPath: "/Users/barry/Downloads/ics/random/",
    type: 2,
  },
]
```

**Comment by sebjulliand** [comment]
Bloody hell...more Windows/POSIX discrepencies 😅 I'll check it out tomorrow.

**Comment by worksofliam** [comment]
@sebjulliand I am looking into it now. Doesn't make much sense because your code makes sense.

**Comment by sebjulliand** [comment]
> @sebjulliand I am happy with this so I am going to merge. Thanks for solving this so quickly!

You're welcome. You got me laughing there 🤣

**Pull request merged**
