### PR TITLE
Remove extra echo line in the PASE terminal head

### PR DESCRIPTION
**Pull request by BoykaZhu**
### Changes

In **Terminal.ts**, filter out the extra **echo** without printing it. Now the PASE terminal welcome message looks clearer.
image

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation. 
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

No doc points in https://codefori.github.io/docs/#/ need to be updated.

bz.

### CODE REVIEW

**Comment by worksofliam** [comment]
Looks ok to me.

image

@codefori/core Can I get a second opinion?

**Review by worksofliam — APPROVED** [review]

**Comment by chrjorgensen** [comment]
@worksofliam Looking okay to me - only issue (not caused by this change!) is that the welcome message only appears from the second PASE terminal started and does not appear in the first terminal started?

**Comment by worksofliam** [comment]
@chrjorgensen That is odd. I just tried spinning up 8 new terminals to get it but didn't get the same result.

**Comment by chrjorgensen** [comment]
@worksofliam It's okay now - don't know why, but after several attempts where the welcome message did not appear on first PASE terminal, now it appears everytime... again, nothing to do with this PR, so go ahead and merge! :smiley:

**Pull request merged**
