### PR TITLE
Correctly handle source members with variant characters in their name

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Fixes https://github.com/codefori/vscode-ibmi/issues/1935

Member names used to be uppercased regarless of the variant characters they may contain. Turns out that `à` is one of CCSID 297 (French) variant chars and it gets uppercased to `À`, which raises a `member not found` error.

This PR adds a new `upperCaseName` method to the `IBMi` class to correctly uppercase names, preservingthe variant chars case.

### How to test this PR
1. Set PASE_LANG environment variable to `FR_FR`
2. Open a connection with a profile whose CCSID is `297`
3. Try to open a member with one or more `à` in its name

### Checklist
* [x] have tested my change
* [ ] have created one or more test cases

### CODE REVIEW

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@sebjulliand I gave the PR a spin, but had no success... 😞 

With or without SQL enabled, when I tried to open a member having `à` in the name, I got the following error:

billede

The member name is correct in the list:

billede

???

Does it work at your end? Could be my system setup...

**Comment by sebjulliand** [comment]
@chrjorgensen check out my comment here: https://github.com/codefori/vscode-ibmi/issues/1935#issuecomment-2003641178

I'll add a commit to this PR with the copy to a temporary member (I managed to open the member, I just need to apply the same logic when saving). We'll see how it goes (I'll un-draft the PR then).

**Comment by sebjulliand** [comment]
@chrjorgensen you can give it another try; I managed to open and save my member with a `à` using this patch.

**Comment by sebjulliand** [comment]
@chrjorgensen you're right, let's reduce the scope only to those who use dangerous variants 😅

**Comment by sebjulliand** [comment]
@chrjorgensen there you go

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand I can confirm being able to open and edit and save members having `à` in the member name when I simulate being French (CCSID 297 etc) when running your PR. 👍 

Approved - merge at will... 😃

**Comment by sebjulliand** [comment]
Thank you @chrjorgensen !

**Pull request merged**
