### PR TITLE
Added Refresh option to actions

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/658

This PR adds a new `Refresh` options to actions.
image

When this option is set to something else than `no`, then a refresh can occur after the action is done, if the action is run on a Browser item.

- `Parent` : the direct parent container of the item is refreshed (e.g. Source File, Library, Folder)
- `Filter` : the parent filter of the item is refreshed
- `Browser` : the browser containing the item is entirely refreshed

@chrjorgensen : there are a few new translations required for the `da` locale 😉 

Note: this PR must be merged after https://github.com/codefori/vscode-ibmi/pull/1611 - it will be a draft until then.

### Checklist
* [x] have tested my change
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
@sebjulliand I will do the Danish translations, just need some clarification for the refresh: I thought a refresh was always done after running an action. Is it not? And what are the new default?

**Comment by sebjulliand** [comment]
> @sebjulliand I will do the Danish translations, just need some clarification for the refresh: I thought a refresh was always done after running an action. Is it not? And what are the new default?

Nope, no refresh happened so far (hence https://github.com/codefori/vscode-ibmi/issues/658); so this adds the refresh capability. and by default, no refresh happens (all actions default to `no`).

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand Looking good to me. :+1: 

I made the Danish translations (in a few attempts) and merged the master branch into this PR to resolve a conflict.

Please promote the PR from draft when you feel like it, and I will approve and merge.

**Comment by sebjulliand** [comment]
Brilliant, thank you so much @chrjorgensen ! I'll wait for https://github.com/codefori/vscode-ibmi/pull/1611 to be approved and merged before promoting this one as this code relies on some types shared by both browsers (i.e. `BrowserItem`) but only in TypeScript.

**Pull request merged**
