### PR TITLE
Add action to open location after download of members/streamfiles

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
This PR adds an `Open` button on the notification shown after a successful streamfile/member download.
image

Cliking on `Open` will reveal the location of the downloaded file(s) in the OS native file explorer.

### How to test this PR
1. Download a member/streamfile
2. Click on open
3. Download a source physical file/multiple streamfiles
4. Click open

### Checklist
* [x] have tested my change

### CODE REVIEW

**Comment by worksofliam** [comment]
Where did you get this branch name from? :o

`fix/memberVariantCharacters`

Testing now!

**Review by worksofliam — APPROVED** [review]
Code looks good - and working on my mac! Nice PR!

image

**Comment by sebjulliand** [comment]
> Where did you get this branch name from? :o
> 
> `fix/memberVariantCharacters`
> 
> Testing now!

Ugh, I didn't pay attention and used a branch that was used for another PR and deleted in the meantime 😥

**Comment by sebjulliand** [comment]
> Code looks good - and working on my mac! Nice PR!
> image

Thanks mate! Merging!

**Pull request merged**
