### PR TITLE
Added quickpick to select upload type

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
Resolves https://github.com/codefori/vscode-ibmi/issues/1833

Since Windows and Linux don't support showing an Open dialog for selecting both folders and files, running the `Upload` action from the IFS Browser will now first show a quick pick to select if the user wants to upload files or folders:
image

Once the type is selected, the corresponding Open dialog is opened and the upload process can carry on as usual.

@chrjorgensen : I'll need your expertise to translate three new sentences in Danish as well as modifying an existing one. Thanks!

### Checklist
* [x] have tested my change

### CODE REVIEW

**Review by chrjorgensen — APPROVED** [review]
@sebjulliand Works as expected - as expected! 😉 

Approved and merged...

**Comment by sebjulliand** [comment]
> @sebjulliand Works as expected - as expected! 😉
> 
> Approved and merged...

Thank you mate!

**Comment by jhollon-jh** [comment]
Thank you for fixing this issue!

**Comment by sebjulliand** [comment]
> Thank you for fixing this issue!

You're welcome! 👍🏻

**Pull request merged**
