### PR TITLE
Updated `vscode-elements` and fixed Private Key storage

### PR DESCRIPTION
**Pull request by sebjulliand**
### Changes
This PR bumps `vscode-elements` to `1.8.0` (and updates the package name from `@bendera/vscode-webview-elements` to `@vscode-elements/elements`.

The CustomUI code has been updated according to the changed made since version `0.12.0`.

It also fixes an issue that prevented connections private key path from being saved (after saving, the path would be `undefined`).
image

#### Test the private key setting
1. Edit a connection
2. Set a private key
3. Save
4. Re-open the connection for edition: the private path must be stored correctly and shown in the settings

#### Check the UI
- Open the `Actions` management screen
- Open the connection settings
- Open the custom variables editor

### Checklist
* [x] have tested my change

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebjulliand I am not sure what the deal is here, but when I run `npm i` on this branch it just hangs. If I switch back to `master` it runs instantly.

**Comment by sebjulliand** [comment]
My bad...I ran npm I at work and it kept work's npm repository URL...I'll fix it asap.

**Comment by sebjulliand** [comment]
@worksofliam there, fixed. I added a `.npmrc` file to prevent this from happening to anybody.

**Comment by julesyan** [comment]
It no longer saves a new private key properly, after re-picking my private key the connection no longer works. It looks to be setting a fake path to the new private key. I tested this function works properly on the master branch. 
I am on a mac if that makes any difference
image

**Comment by sebjulliand** [comment]
Implemented by #2386

**Pull request closed without merging**
