### PR TITLE
Fix for issue 1600: Debug session does not start if the command default have been changed to MSGQ(*WRKSTN) for the SBMJOB command

### LINKED ISSUE #1600: Debug session does not start if the command default have been changed to MSGQ(*WRKSTN) for the SBMJOB command
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
Debug session does not star if the command default have been changed to MSGQ(*WRKSTN) for the SBMJOB command.
When start debugging a program, the debug stops with the following messages:
**_CPF1245: MSGQ(*WRKSTN) not valid. MSGQ(*NONE) used._**

This is just a warning messages and the submit job command (SBMJOB) will change the MSGQ parameter to *NONE, but the code for i debugger can not handle this an will display a pop up the messages and the only valid choices is Open 'Launch.json' and Cancel.

**To Reproduce**
1. Change the command default for the SBMJOB command: _**CHGCMDDFT  CMD(SBMJOB) NEWDFT('MSGQ(*WRKSTN)')**_
2. Debug a program
3. See the pop up dialog with the error

**Expected behavior**
This messages should not prevent the debugging to continue.
I guess the easiest way to fix this is to simply change the SBMJOB in the debugger code and add the MSGQ parameter with the shipped value: MSGQ(*USRPRF):

"startBatchJobCommand": `SBMJOB CMD(${currentCommand}) INLLIBL(${config?.libraryList.join(` `)}) CURLIB(${config?.currentLibrary}) JOBQ(QSYSNOMAX) MSGQ(*USRPRF)`,

**Screenshots**

**Environment (please complete the following information):**
 - Extension version: 2.4.0
 - IBM i OS version : 7.5

IBM i debug

### PR DESCRIPTION
**Pull request by krka01**
### Changes
Make sure the submit job command is called using MSGQ(*USRPRF) when starting a debug session.

Closes #1600

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Review by chrjorgensen — CHANGES_REQUESTED** [review]
@krka01 Thank you for the contribution and fix for #1600. 👍 

Before I can test and approve, please change the commit message to describe the change, like `Submit debug job using MSGQ(*USRPRF)` or similar...

**Comment by krka01** [comment]
@chrjorgensen I have changed the commit message as you suggetsed

**Review by chrjorgensen — APPROVED** [review]
@krka01 Looking good - thanks!

**Comment by chrjorgensen** [comment]
@krka01 Next time, create a new branch for your changes - this makes it easier for you to switch between the main code and your fixes. 😃 

I can recommend this guide for how to work with github projects (followed it myself... 😉):
https://www.dataschool.io/how-to-contribute-on-github/

**Pull request merged**
