### PR TITLE
update vscode-test to @vscode/test-electron

### PR DESCRIPTION
**Pull request by jwoehr**
### Changes

Updated package.json
- version 2.6.1
- change vscode-test to @vscode/test-electron

Hope this is useful. Trying to get into the groove of building and testing codefori. 

### Checklist

* [x ] have tested my change
* [ n/a] updated relevant documentation
* [ n/a] Remove any/all `console.log`s I added
* [ x] eslint is not complaining
* [ x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ n/a] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by chrjorgensen** [comment]
Hi @jwoehr !

Thank you for your contribution - really appreciated!

Could you resolve the conflicts, so we can get this merged? :smiley:

**Comment by chrjorgensen** [comment]
Hm, better leave this to the build experts... @worksofliam @sebjulliand

**Comment by sebjulliand** [comment]
As far as I can tell, we don't use VSCode's test framework; we use our own.
@jwoehr you can remove it completely 😅

**Comment by jwoehr** [comment]
Think I have it now :)

**Review by sebjulliand — APPROVED** [review]
Looks good to me now @jwoehr !
I love a good cleanup. Thanks Jack!

**Pull request merged**
