### PR TITLE
Use both hostname and ip address for debug service certificate

### PR DESCRIPTION
**Pull request by william-xiang**
### Changes

Use both hostname and ip address when creating the debug service certificate, so users can use either one of them for connection. 

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
This likely needs to wait for #1657 to be merged first.

**Review by worksofliam — APPROVED** [review]
@william-xiang I have tested it and it's working great.

```
/QIBM/ProdData/IBMiDebugService/bin/certs: openssl genrsa -out debug_service_ca.key 2048 && openssl req -x509 -new -nodes -key debug_service_ca.key -sha256 -days 1825 -out debug_service_ca.pem -subj '/CN=mybox' && openssl genrsa -out debug_service.key 2048 && openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=mybox' && openssl x509 -req -in debug_service.csr -CA debug_service_ca.pem -CAkey debug_service_ca.key -CAcreateserial -out debug_service.crt -days 1095 -sha256 -sha256 -req -extfile <(printf "subjectAltName=DNS:mybox,IP:9.5.10.206") && openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:mybox
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": "Generating RSA private key, 2048 bit long modulus (2 primes)\n...........................................................+++++\n...........+++++\ne is 65537 (0x010001)\nGenerating RSA private key, 2048 bit long modulus (2 primes)\n..................................................................................................+++++\n.......+++++\ne is 65537 (0x010001)\nSignature ok\nsubject=CN = mybox\nGetting CA Private Key"
}
```

If you are happy with your testing, I am happy to merge.

**Comment by william-xiang** [comment]
@worksofliam I see you used the hostname for the testing. I guess with this PR #1657, when using the IP address and secure is enabled, the user will get an warning message about changing to use hostname. Do we still want to keep this message?

**Comment by worksofliam** [comment]
@william-xiang I can try creating the certificates with an IP address today as well. Let me post back when I've done that.

**Comment by worksofliam** [comment]
Just tested new certs, connected with an IP in secure mode and it works great!

Let's merge.

**Pull request merged**
