### PR TITLE
Use SQL methods to fetch object data

### PR DESCRIPTION
**Pull request by worksofliam**
### Changes

* Replace `DSPFD` and `DSPOBJD` with new SQL to fix CCSID issues.

### To do

* [x] Fix filter issue (only 3/4 tests are passing)
* [x] Correct invalid columns in the new SQL

### How to test this PR

Examples:

1. Run the test cases
2. Ensure Object Browser filters work

### Checklist

* [x] have tested my change
* [ ] have created one or more test cases
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/codefori/vscode-ibmi/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by worksofliam** [comment]
@chrjorgensen @sebjulliand Any chance you can help me fix the new SQL?

**Comment by chrjorgensen** [comment]
@worksofliam I changed the SQL's for object lists - and they seem to work.

Can you verify on your test system?

I tested on PUB400 and noticed, that texts were returned in German (CCSID 273) even though my user has Danish (CCSID 277). I hope SQL_TO_CSV will fix that?

**Comment by chrjorgensen** [comment]
@worksofliam Already found an error - when multiple libraries are specified in the filter, nothing shows up in the list...

Will investigate this...

**Comment by worksofliam** [comment]
@chrjorgensen thanks for your commits!!

I think I need to create a test branch that merges this and our component branch to see if it solves the issue. I believe it will. I will let you know by Monday.

**Comment by edmundreinhardt** [comment]
What about DSPFFD in getting record formats, is that being done in a different PR?

**Comment by worksofliam** [comment]
@edmundreinhardt i believe that is done in vscode-rpgle, not in vscode-ibmi.

**Comment by chrjorgensen** [comment]
> i believe that is done in vscode-rpgle, not in vscode-ibmi.

@worksofliam Wouldn't it be better to have the `DSPFFD` function in vscode-ibmi, supporting all language extensions? vscode-clle could also use such a function to feed data to the outline view when `DCLF`is being used...

**Comment by worksofliam** [comment]
@chrjorgensen yep, that could be the long term strategy for sure. Nothing this PR will solve.

**Comment by worksofliam** [comment]
@chrjorgensen @sebjulliand I believe my work here is done. The tests are passing.

Please have one last sweep, and test as you please, and let's get this merged. Thanks!

image

**Comment by sebjulliand** [comment]
> @chrjorgensen @sebjulliand I believe my work here is done. The tests are passing.

Famous last words 🤣
One test fails and it's a bug related to this PR:
image

I'm looking into it; it should be an easy fix.

**Comment by sebjulliand** [comment]
@worksofliam you're good to go. Code looks good too.
image

I tested it and it runs fine in all cases I had. Merge whenever you want.

A question, maybe for another PR: to speed up the *SRCPF loading a bit, shouldn't we skip the joins on `SYSTABLESTAT` and 
`SYSCOLUMNS` views and only resolve the information they give (namely CCSID and source length) when the item tooltip is displayed? (using `resolveTreeItem`, like it's done in the debug view)?

**Review by sebjulliand — APPROVED** [review]

**Comment by worksofliam** [comment]
@sebjulliand I don't know if we can because I believe we use the source length from the result elsewhere. But, I will take a look at that in another PR.

**Pull request merged**
